---
title: "Get expectation for the UniSEMPGS bias analyses"
author: "Xuanyu"
date: "04/08/2025"
output: html_document
---

```{r setup, include=FALSE}
#source("Simulate.Multivariate.NOLD.AM.FUNCTIONS_May2021-mck7.R")
```

```{r parameters, include=TRUE}
conditionNames <- c("onlyAM", "onlyVT", "bothAMVT", "bothAMVT_StrongCrossTrait", "OnlyUni")

startingParamList1 <- list(vg1 = rep(.64,5),
						   vg2 = rep(.36,5),
						   am11 = c(rep(0.4,3),.05,.4),
						   am12 = c(.2,0,.2,.4,0),
						   am21 = c(.2,0,.2,.4,0), 
						   am22 = c(rep(0.3,3),.1,.2),
						   f11 = c(rep(0.15,3),0,.3),
						   f12 = c(0,.1,.1,.3,0),
						   f21 = c(0,.05,.05,.25,0), 
						   f22 = c(rep(0.1,4),.1),
						   Nfam = rep(3e4, 5),
						   rg = rep(0,5),
						   re = rep(0,5),
						   prop.h2.latent1 = rep(.60/.64,5),
						   prop.h2.latent2 = rep(.8,5),
                           vg1_last = rep(.49,5),
                           vg2_last = rep(.36,5),
                           rg_last = rep(0,5),
                           prop.h2.latent1_last = rep(.3/.49,5),
                           prop.h2.latent2_last = rep(.8,5))


```

```{r iterativeMath}
iterativeMath <- function(condition=1, startingParam = startingParamList1){
    startingParamList1 <- startingParam
    condition = condition
    pathName = "testdata"
    # WILDCARD parameters
	pop.size <-  startingParamList1["Nfam"][[1]][[condition]] #maybe something like 2e4, or 20000, when running for real
	num.cvs <- 200 #maybe 25
	seed <- 62*condition
	num.gen <-  20 #8 should be sufficient to get to AM equilibrium
	avoid.inb <- TRUE #avoid inbreeding?
	save.covariances <- TRUE #save the covariance matrices?
	save.history <- TRUE #save the data for each generation?
	min.maf <- .1 #.2 for real
	max.maf <- .5 #.5

	#USER INPUT VARIABLES
	#VG
	vg1 <- startingParamList1["vg1"][[1]][[condition]] #trait 1 vg
	vg2 <- startingParamList1["vg2"][[1]][[condition]] #trait 2 vg
	rg <- startingParamList1["rg"][[1]][[condition]] #genetic CORRELATION @t0 bw trait 1 and trait 2 for both obs. PGS and latent PGS (assumed to be the same). NOTE: this is NOT the full rg at t0. It is the rg bw PGSs, and the rg bw LGSs. The full rg may be a bit different (Simpson's paradox)
	(k2.matrix <- matrix(c(1,rg,rg,1),nrow=2,byrow=T)) #k2 matrix is 2 * k matrix - i.e., genotypic (instead of haplotypic) var/covar at t0
	prop.h2.latent1 <- startingParamList1["prop.h2.latent1"][[1]][[condition]] #  trait 1, e.g., height
	prop.h2.latent2 <- startingParamList1["prop.h2.latent2"][[1]][[condition]] # trait 2, e.g., IQ
    # VG at last generation
    vg1_last <- startingParamList1["vg1_last"][[1]][[condition]] #trait 1 vg at last generation
    vg2_last <- startingParamList1["vg2_last"][[1]][[condition]] #trait 2 vg at last generation
    rg_last  <- startingParamList1["rg_last"][[1]][[condition]] 
    k2.matrix_last <- matrix(c(1,rg_last,rg_last,1),nrow=2,byrow=T) #k2 matrix is 2 * k matrix - i.e., genotypic (instead of haplotypic) var/covar at t0
    j2.matrix_last <- k2.matrix_last
    prop.h2.latent1_last <- startingParamList1["prop.h2.latent1_last"][[1]][[condition]] #  trait 1, e.g., height at last generation
    prop.h2.latent2_last <- startingParamList1["prop.h2.latent2_last"][[1]][[condition]] # trait 2, e.g., IQ at last generation


	#AM - these are NOT the mu copaths. They are the CORRELATIONS between male & female traits
	am11 <-  startingParamList1["am11"][[1]][[condition]] #height.m-height.f am across 2 its
	am12 <-  startingParamList1["am12"][[1]][[condition]] #height.m-iq.f; e.g., tall males choose smart females
	am21 <-  startingParamList1["am21"][[1]][[condition]] #iq.m-height.f
	am22 <-  startingParamList1["am22"][[1]][[condition]] #iq.m - iq.f

	#VT
	f11 <- startingParamList1["f11"][[1]][[condition]] # regression of offspring trait 1 F on parental trait 1
	f12 <- startingParamList1["f12"][[1]][[condition]] # regression of offspring trait 1 F on parental trait 2
	f21 <- startingParamList1["f21"][[1]][[condition]] # regression of offspring trait 2 F on parental trait 1
	f22 <- startingParamList1["f22"][[1]][[condition]] # regression of offspring trait 2 F on parental trait 2

	#E
	re <- startingParamList1["re"][[1]][[condition]] #environmental CORRELATION between trait 1 & trait 2

	# IMPLIED variables
	#This section just converts the above inputs into matrices in our algebra

	#Create lower delta matrix (d stands for delta)
	(vg.obs1 <- vg1*(1-prop.h2.latent1))
	(vg.obs2 <- vg2*(1-prop.h2.latent2))
	(covg.obs <- rg*sqrt(vg.obs1)*sqrt(vg.obs2))
	d11 <- sqrt(vg.obs1)
	#d21 <- covg.obs/d11
	d21 <- 0 #new way
	d22 <- sqrt(vg.obs2 - d21^2)
	(delta.mat <- matrix(c(d11,0,d21,d22),byrow=T,nrow=2))
	(vg.obs <- delta.mat %*% k2.matrix %*% t(delta.mat)) #Check
	matrix(c(vg.obs1,covg.obs,covg.obs,vg.obs2),nrow=2) #Check
    #Create lower delta matrix for the last generation
    (vg.obs1_last <- vg1_last*(1-prop.h2.latent1_last))
    (vg.obs2_last <- vg2_last*(1-prop.h2.latent2_last))
    (covg.obs_last <- rg_last*sqrt(vg.obs1_last)*sqrt(vg.obs2_last))
    d11_last <- sqrt(vg.obs1_last)
    #d21_last <- covg.obs_last/d11_last
    d21_last <- 0 #new way
    d22_last <- sqrt(vg.obs2_last - d21_last^2)
    (delta.mat_last <- matrix(c(d11_last,0,d21_last,d22_last),byrow=T,nrow=2))
    vg.obs_last <- delta.mat_last %*% k2.matrix_last %*% t(delta.mat_last) #Check

	#Create lower a matrix
	(vg.lat1 <- vg1*(prop.h2.latent1))
	(vg.lat2 <- vg2*(prop.h2.latent2))
	(covg.lat <- rg*sqrt(vg.lat1)*sqrt(vg.lat2))
	a11 <- sqrt(vg.lat1)
	#a21 <- covg.lat/a11
	a21 <- 0 #new way
	a22 <- sqrt(vg.lat2 - a21^2)
	(a.mat <- matrix(c(a11,0,a21,a22),byrow=T,nrow=2))
	(vg.lat <- a.mat %*% k2.matrix %*% t(a.mat)) #Check
	matrix(c(vg.lat1,covg.lat,covg.lat,vg.lat2),nrow=2) #Check
    #Create lower a matrix for the last generation
    (vg.lat1_last <- vg1_last*(prop.h2.latent1_last))
    (vg.lat2_last <- vg2_last*(prop.h2.latent2_last))
    (covg.lat_last <- rg_last*sqrt(vg.lat1_last)*sqrt(vg.lat2_last))
    a11_last <- sqrt(vg.lat1_last)
    #a21_last <- covg.lat_last/a11_last
    a21_last <- 0 #new way
    a22_last <- sqrt(vg.lat2_last - a21_last^2)
    (a.mat_last <- matrix(c(a11_last,0,a21_last,a22_last),byrow=T,nrow=2))
    (vg.lat_last <- a.mat_last %*% k2.matrix_last %*% t(a.mat_last)) #Check

	#Find the total genetic covariance
	#(covg <- vg.obs[1,2] + vg.lat[1,2])
	(covg.mat <- vg.obs + vg.lat)
	a.mat %*% k2.matrix %*% t(a.mat) + delta.mat %*% k2.matrix %*% t(delta.mat) #check
    
    # covg for the last generation
    (covg.mat_last <- vg.obs_last + vg.lat_last)

	#Create E lower matrix
	ve1 <- 1 - vg1
	ve2 <- 1 - vg2
	(cove <- re*sqrt(ve1*ve2))
	(cove.mat <- matrix(c(ve1,cove,cove,ve2),nrow=2,byrow=T))
	#Create var-covar(Y) @t0. NOTE: we define the base population as the population before any AM or VT has occurred.
	(COVY <- covg.mat+cove.mat)
	a.mat %*% k2.matrix %*% t(a.mat) + delta.mat %*% k2.matrix %*% t(delta.mat) + cove.mat  #Check; these two should have 1 on the diagonals and the off-diags should be exactly the same if we've done everything above correctly.
	#Note that our actual model estimates k and j separately, and thus our model does not make the assumption made in this simulation that the observed and latent rg at t0 are the same (or does it? do we actually estimate j12, or do we set it equal to k12?)


	#Note: we will add influences of AM and VT AFTER time 0
	#AM - make sure to change am.list if you want AM to change across generations
	(mate.cor.mat <- matrix(c(am11,am12,am21,am22),nrow=2,byrow=T))
	#am.list <- rep(list(mate.cor.mat),num.gen+1)

	#VF
	(f.mat <- matrix(c(f11,f12,f21,f22),nrow=2,byrow=T))
	(covf.mat <- 2 * (f.mat %*% COVY %*% t(f.mat)))
    

    gens = 15
    a.t0 <- a.mat
    delta.t0 <- delta.mat
    j.t0 <- k2.matrix*.5
    k.t0 <- k2.matrix*.5
    k.last <- k2.matrix_last*.5
    j.last <- k2.matrix_last*.5
    f.t0 <- f.mat
    rmate.t0 <- mate.cor.mat
    covE.t0 <- cove.mat
    #rmate.t0 <- obs.cor

    #Define and initialize at t0 parameters that evolve
    exp.gc <- exp.hc <- exp.ic <- exp.gt <- exp.ht <- exp.itlo <- exp.itol <- exp.w <- exp.v <- exp.VY <- exp.VY.diagonal <- exp.corVY<- exp.mu <- exp.VF <- exp.Omega <- exp.Gamma <- exp.thetaT <- exp.thetaNT <- exp.thetaLT <- exp.thetaLNT <- mate.cov <- mate.cor <- exp.VGO <- exp.VGL <- exp.COVLO <- vector(mode="list",length=gens-1)
    #initialize parameters that begin as 0's in base population (before VT and AM)
    exp.VGO[[1]] <- exp.VGL[[1]] <- exp.COVLO[[1]] <- exp.gc[[1]] <- exp.hc[[1]] <- exp.ic[[1]] <- exp.w[[1]] <- exp.v[[1]] <- matrix(0,nrow=2,ncol=2)
    # define the true 4X4 covariance matrix for Vy at t0
    exp.covY.full <- exp.corY.full <- exp.covY.full.diagonal <- vector(mode="list",length=gens-1)
    #initialize parameters that are non-zero in base population (think of these as the first parents to pass on VT and engage in AM)
    (exp.VY[[1]] <- COVY)
    (exp.VY.diagonal[[1]] <- diag(diag(exp.VY[[1]])))
    (exp.VF[[1]] <- covf.mat)
    (exp.mu[[1]] <- solve(COVY) %*% rmate.t0 %*% solve(t(COVY)))
    (mate.cov[[1]] <- COVY %*% exp.mu[[1]] %*% COVY )
    (exp.covY.full[[1]] <- rbind(cbind(exp.VY[[1]], t(mate.cov[[1]])),cbind(mate.cov[[1]], exp.VY[[1]])))
    (exp.corY.full[[1]] <- cov2cor(exp.covY.full[[1]]))
    mate.cor[[1]] <- mate.cov[[1]]/COVY
    mate.cor[[1]][1,2] <- mate.cov[[1]][1,2]/sqrt(COVY[1,1]*COVY[2,2])
    mate.cor[[1]][2,1] <- mate.cov[[1]][2,1]/sqrt(COVY[1,1]*COVY[2,2])
    mate.cor[[1]]
# specify the model want to check, model 1 or 2
model = 2

if (model == 1){
    # if you want to use the average of delta.t0%*%t(exp.Omega[[it]]) + exp.Omega[[it]]%*%t(delta.t0) or only use one of them
    if(average){
        for(it in 2:gens){
        (exp.Omega[[it]] <- 2*delta.t0%*%exp.gc[[it-1]] + delta.t0 %*% k.t0 + .5*exp.w[[it-1]] )
        cat("Omega",it,"\n",exp.Omega[[it]],"\n")
        (exp.VY[[it]] <- delta.t0%*%t(exp.Omega[[it]]) + exp.Omega[[it]]%*%t(delta.t0) + exp.VF[[it-1]] + 0.5*exp.w[[it-1]]%*%t(delta.t0) + 0.5*delta.t0%*%t(exp.w[[it-1]]) + covE.t0 )
        cat("VY","\n")
        print(exp.VY[[it]])
        # two potential ways: fix mu or fix mate.cor
        exp.VY.diagonal[[it]] <- exp.VY[[it]]
        exp.VY.diagonal[[it]][1,2] <- 0
        exp.VY.diagonal[[it]][2,1] <- 0

        exp.covY.full.diagonal[[it]] <- cbind(rbind(exp.VY.diagonal[[it]],matrix(0,2,2)),rbind(matrix(0,2,2),exp.VY.diagonal[[it]]))

        if(fixedMateCor){
            exp.corVY[[it]] <- cov2cor(exp.VY[[it]])
            exp.corY.full[[it]] <- exp.corY.full[[1]]
            exp.corY.full[[it]][1,2] <- exp.corVY[[it]][1,2]
            exp.corY.full[[it]][2,1] <- exp.corVY[[it]][2,1]
            exp.corY.full[[it]][3,4] <- exp.corVY[[it]][1,2]
            exp.corY.full[[it]][4,3] <- exp.corVY[[it]][2,1]
            #exp.covY.full[[it]] <- cor2cov(exp.corY.full[[it]],exp.VY[[it]][1,1],exp.VY[[it]][2,2],exp.VY[[it]][1,1],exp.VY[[it]][2,2]) 
            exp.covY.full[[it]] <- sqrt(exp.covY.full.diagonal[[it]]) %*% exp.corY.full[[it]] %*% sqrt(exp.covY.full.diagonal[[it]])
            mate.cov[[it]] <- exp.covY.full[[it]][3:4,1:2] ## this is the mate.cov fixing mate.cor
            mate.cor[[it]] <- exp.corY.full[[1]][3:4,1:2]
            (exp.mu[[it]] <- solve(exp.VY[[it]]) %*% mate.cov[[it]] %*% solve(t(exp.VY[[it]]))) 
            
        } else {
            exp.mu[[it]] <- exp.mu[[1]]
            mate.cov[[it]] <- exp.VY.diagonal[[it]] %*% exp.mu[[it]] %*% exp.VY.diagonal[[it]] ## this is the mate.cov fixing mu
            exp.covY.full[[it]] <- rbind(cbind(exp.VY[[it]], mate.cov[[it]]),cbind(mate.cov[[it]], exp.VY[[it]]))
            exp.corY.full[[it]] <- cov2cor(exp.covY.full[[it]])
            
            mate.cor[[it]] <- exp.corY.full[[it]][3:4,1:2]
            #mate.cor[[it]] <- solve(sqrt(exp.VY.diagonal[[it]]))%*%mate.cov[[it]]%*%solve(sqrt(exp.VY.diagonal[[it]]))
        }
        
        (exp.gt[[it]] <- t(exp.Omega[[it]])%*%exp.mu[[it]]%*%exp.Omega[[it]])
        cat("gt",it,"\n",exp.gt[[it]],"\n")
        (exp.gc[[it]] <- .5*(exp.gt[[it]] + t(exp.gt[[it]])))


        (exp.w[[it]] <- 2*f.t0%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it]]%*%exp.mu[[it]]%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it]]%*%t(exp.mu[[it]])%*%exp.Omega[[it]])
        cat("w", "\n")
        print(exp.w[[it]])
        # (exp.thetaNT[[it]] <- 2*(exp.Omega[[it]] - delta.t0 %*% k.t0)) # the expected value in this script
        (exp.thetaNT[[it]] <- 2*delta.t0%*%exp.gt[[it]] + delta.t0%*%exp.gt[[it]] + delta.t0%*%t(exp.gt[[it]]) + exp.w[[it]])
        (exp.thetaT[[it]] <- 2*delta.t0%*%exp.gt[[it]] + 2*delta.t0*k.t0 + delta.t0%*%exp.gt[[it]] + delta.t0%*%t(exp.gt[[it]]) + exp.w[[it]])
        (exp.VF[[it]] <- 2*f.t0%*%exp.VY[[it]]%*%t(f.t0) + f.t0%*%exp.VY[[it]]%*%exp.mu[[it]]%*%exp.VY[[it]]%*%t(f.t0) +  f.t0%*%exp.VY[[it]]%*%t(exp.mu[[it]])%*%exp.VY[[it]]%*%t(f.t0))
        cat("VF","\n")
        print(exp.VF[[it]])
        (exp.VGO[[it]] <- 2*delta.t0%*%k.t0%*%t(delta.t0) + 4*delta.t0%*%exp.gc[[it]]%*%t(delta.t0))

        # mate.cor[[it]] <- mate.cov[[it]]/exp.VY[[it]] ## this is the mate.cor fixing mu
        # mate.cor[[it]][1,2] <- mate.cov[[it]][1,2]/(sqrt(exp.VY[[it]][1,1])*sqrt(exp.VY[[it]][2,2]))
        # mate.cor[[it]][2,1] <- mate.cov[[it]][2,1]/(sqrt(exp.VY[[it]][1,1])*sqrt(exp.VY[[it]][2,2]))
        cat("mate.cov",it,"\n",mate.cov[[it]],"\n")
        cat("mate.cor",it,"\n",mate.cor[[it]],"\n")
        cat("mu",it,"\n",exp.mu[[it]],"\n")
        cat("VF",it,"\n",exp.VF[[it-1]],"\n")
        cat("covFull",it,"\n")
        print(exp.covY.full[[it]])
        cat("corFull",it,"\n")
        print(exp.corY.full[[it]])
    } } else {
        #the math when using only single path tracing approach
        for(it in 2:gens){
        (exp.Omega[[it]] <- 2*delta.t0%*%exp.gc[[it-1]] + delta.t0 %*% k.t0 + .5*exp.w[[it-1]] )
        (exp.gt[[it]] <- t(exp.Omega[[it]])%*%exp.mu[[it-1]]%*%exp.Omega[[it]])
        (exp.gc[[it]] <- .5*(exp.gt[[it]] + t(exp.gt[[it]])))
        (exp.w[[it]] <- 2*f.t0%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it-1]]%*%exp.mu[[it-1]]%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it-1]]%*%t(exp.mu[[it-1]])%*%exp.Omega[[it]])
        # (exp.thetaNT[[it]] <- 2*(exp.Omega[[it]] - delta.t0 %*% k.t0)) # the expected value in this script
        (exp.thetaNT[[it]] <- 2*delta.t0%*%exp.gt[[it]] + delta.t0%*%exp.gt[[it]] + delta.t0%*%t(exp.gt[[it]]) + exp.w[[it]])
        (exp.thetaT[[it]] <- 2*delta.t0%*%exp.gt[[it]] + 2*delta.t0*k.t0 + delta.t0%*%exp.gt[[it]] + delta.t0%*%t(exp.gt[[it]]) + exp.w[[it]])
        (exp.VF[[it]] <- 2*f.t0%*%exp.VY[[it-1]]%*%t(f.t0) + f.t0%*%exp.VY[[it-1]]%*%exp.mu[[it-1]]%*%exp.VY[[it-1]]%*%t(f.t0) +  f.t0%*%exp.VY[[it-1]]%*%t(exp.mu[[it-1]])%*%exp.VY[[it-1]]%*%t(f.t0))
        (exp.VY[[it]] <- 2*delta.t0%*%t(exp.Omega[[it]]) + exp.VF[[it]] + exp.w[[it]]%*%t(delta.t0) + covE.t0 )
        (exp.VGO[[it]] <- 2*delta.t0%*%k.t0%*%t(delta.t0) + 4*delta.t0%*%exp.gc[[it]]%*%t(delta.t0))
        
        # two potential ways: fix mu or fix mate.cor
        if(fixedMateCor){
            mate.cov[[it]] <- cor2cov(rmate.t0,exp.VY[[it]][1,1],exp.VY[[it]][2,2]) ## this is the mate.cov fixing mate.cor
            (exp.mu[[it]] <- solve(exp.VY[[it]]) %*% mate.cov[[it]] %*% solve(t(exp.VY[[it]]))) 
            mate.cor[[it]] <- rmate.t0
        } else {
            exp.mu[[it]] <- exp.mu[[1]]
            mate.cov[[it]] <- exp.VY[[it]]%*%exp.mu[[it]]%*%exp.VY[[it]] ## this is the mate.cov fixing mu
            mate.cor[[it]] <- cov2cor(mate.cov[[it]])
        }
        # mate.cor[[it]] <- mate.cov[[it]]/exp.VY[[it]] ## this is the mate.cor fixing mu
        # mate.cor[[it]][1,2] <- mate.cov[[it]][1,2]/(sqrt(exp.VY[[it]][1,1])*sqrt(exp.VY[[it]][2,2]))
        # mate.cor[[it]][2,1] <- mate.cov[[it]][2,1]/(sqrt(exp.VY[[it]][1,1])*sqrt(exp.VY[[it]][2,2]))
        cat("mate.cov",it,"\n",mate.cov[[it]],"\n")
        cat("mate.cor",it,"\n",mate.cor[[it]],"\n")
        cat("mu",it,"\n",exp.mu[[it]],"\n")
    }
    }

    EXP <- list(
        Omega=exp.Omega[[gens]],
        theta=exp.thetaNT[[gens]],
        #Gamma=exp.Gamma[[gens]],
        gc=exp.gc[[gens]],
        #hc=exp.hc[[gens]],
        #itlo=exp.itlo[[gens]],
        #itol=exp.itol[[gens]],
        #ic=exp.ic[[gens]],
        VF=exp.VF[[gens]],
        w=exp.w[[gens]],
        #q=exp.q[[gens]],
        VY=exp.VY[[gens]],
        mate.cov=mate.cov[[gens]],
        mu=exp.mu[[gens]],
        VGO=exp.VGO[[gens]]
        #VGL=exp.VGL[[gens]],
        #COVLO=exp.COVLO[[gens]]
        )

        # (cov.fin.gen <- exp.VY[[gens]]%*%exp.mu[[gens]]%*%exp.VY[[gens]])
        # cor.fin.gen <- cov.fin.gen/exp.VY[[gens]]
        # cor.fin.gen[1,2] <- cov.fin.gen[1,2]/(sqrt(exp.VY[[gens]][1,1])*sqrt(exp.VY[[gens]][2,2]))
        # cor.fin.gen[2,1] <- cov.fin.gen[2,1]/(sqrt(exp.VY[[gens]][1,1])*sqrt(exp.VY[[gens]][2,2]))
        # print(cor.fin.gen)
} else {
   for (it in 2:gens){
        (exp.Omega[[it]] <- 2*delta.t0%*%exp.gc[[it-1]] + delta.t0 %*% k.t0 + .5*exp.w[[it-1]] + 2*a.t0%*%exp.ic[[it-1]])
        cat("Omega",it,"\n",exp.Omega[[it]],"\n")
        (exp.Gamma[[it]] <- 2*a.t0%*%exp.hc[[it-1]] + 2*delta.t0%*%t(exp.ic[[it-1]]) + a.t0%*%j.t0 + .5*exp.v[[it-1]])
        cat("Gamma",it,"\n",exp.Gamma[[it]],"\n")

        (exp.VY[[it]] <- 2 * delta.t0 %*% t(exp.Omega[[it]]) + 2 * a.t0 %*% t(exp.Gamma[[it]]) + exp.w[[it-1]] %*% t(delta.t0) + exp.v[[it-1]] %*% t(a.t0) + exp.VF[[it-1]] + covE.t0 )
        cat("VY","\n")
        print(exp.VY[[it]])

        # two potential ways: fix mu or fix mate.cor
        exp.VY.diagonal[[it]] <- exp.VY[[it]]
        exp.VY.diagonal[[it]][1,2] <- 0
        exp.VY.diagonal[[it]][2,1] <- 0

        exp.covY.full.diagonal[[it]] <- cbind(rbind(exp.VY.diagonal[[it]],matrix(0,2,2)),rbind(matrix(0,2,2),exp.VY.diagonal[[it]]))

        exp.corVY[[it]] <- cov2cor(exp.VY[[it]])
        exp.corY.full[[it]] <- exp.corY.full[[1]]
        exp.corY.full[[it]][1,2] <- exp.corVY[[it]][1,2]
        exp.corY.full[[it]][2,1] <- exp.corVY[[it]][2,1]
        exp.corY.full[[it]][3,4] <- exp.corVY[[it]][1,2]
        exp.corY.full[[it]][4,3] <- exp.corVY[[it]][2,1]
        #exp.covY.full[[it]] <- cor2cov(exp.corY.full[[it]],exp.VY[[it]][1,1],exp.VY[[it]][2,2],exp.VY[[it]][1,1],exp.VY[[it]][2,2]) 
        exp.covY.full[[it]] <- sqrt(exp.covY.full.diagonal[[it]]) %*% exp.corY.full[[it]] %*% sqrt(exp.covY.full.diagonal[[it]])
        mate.cov[[it]] <- exp.covY.full[[it]][3:4,1:2] ## this is the mate.cov fixing mate.cor
        mate.cor[[it]] <- exp.corY.full[[1]][3:4,1:2]
        (exp.mu[[it]] <- solve(exp.VY[[it]]) %*% mate.cov[[it]] %*% solve(t(exp.VY[[it]]))) 
        cat("mu")
        print(exp.mu[[it]])
        (exp.gt[[it]] <- t(exp.Omega[[it]])%*%exp.mu[[it]]%*%exp.Omega[[it]])
        cat("gt",it,"\n",exp.gt[[it]],"\n")
        (exp.gc[[it]] <- .5*(exp.gt[[it]] + t(exp.gt[[it]])))
        cat("gc",it,"\n",exp.gc[[it]],"\n")
        (exp.ht[[it]] <- t(exp.Gamma[[it]])%*%exp.mu[[it]]%*%exp.Gamma[[it]])
        cat("ht",it,"\n",exp.ht[[it]],"\n")
        (exp.hc[[it]] <- .5*(exp.ht[[it]] + t(exp.ht[[it]])))  
        cat("hc",it,"\n",exp.hc[[it]],"\n")
        (exp.w[[it]] <- 2*f.t0%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it]]%*%exp.mu[[it]]%*%exp.Omega[[it]] + f.t0%*%exp.VY[[it]]%*%t(exp.mu[[it]])%*%exp.Omega[[it]])
        cat("w", "\n")
        print(exp.w[[it]])
        (exp.v[[it]] <- 2*f.t0%*%exp.Gamma[[it]] + f.t0%*%exp.VY[[it]]%*%exp.mu[[it]]%*%exp.Gamma[[it]] + f.t0%*%exp.VY[[it]]%*%t(exp.mu[[it]])%*%exp.Gamma[[it]])  
        cat("v", "\n")
        print(exp.v[[it]])
        (exp.VF[[it]] <- 2*f.t0%*%exp.VY[[it]]%*%t(f.t0) + f.t0%*%exp.VY[[it]]%*%exp.mu[[it]]%*%exp.VY[[it]]%*%t(f.t0) +  f.t0%*%exp.VY[[it]]%*%t(exp.mu[[it]])%*%exp.VY[[it]]%*%t(f.t0))
        cat("VF","\n")
        print(exp.VF[[it]])
        (exp.itlo[[it]] <- t(exp.Gamma[[it]])%*%exp.mu[[it]]%*%exp.Omega[[it]])
        
        (exp.itol[[it]] <- t(exp.Omega[[it]])%*%exp.mu[[it]]%*%exp.Gamma[[it]])

        (exp.ic[[it]] <- .25*(exp.itol[[it]] + t(exp.itol[[it]]) + exp.itlo[[it]] + t(exp.itlo[[it]])))
        cat("ic",it,"\n",exp.ic[[it]],"\n")
        (exp.VGO[[it]] <- 2*delta.t0%*%k.t0%*%t(delta.t0) + 4*delta.t0%*%exp.gc[[it]]%*%t(delta.t0))
        (exp.VGL[[it]] <- 2*a.t0%*%j.t0%*%t(a.t0) + 4*a.t0%*%exp.hc[[it]]%*%t(a.t0))
        (exp.COVLO[[it]] <- 4*delta.t0%*%t(exp.ic[[it]])%*%t(a.t0) + 4*a.t0%*%exp.ic[[it]]%*%t(delta.t0))
        if(it == gens){
            exp.VY[[it+1]] <- 2*delta.mat_last%*%k.last%*%t(delta.mat_last) + 4*delta.mat_last%*%exp.gc[[it]]%*%t(delta.mat_last) + 2*a.mat_last%*%j.last%*%t(a.mat_last) + 4*a.mat_last%*%exp.hc[[it]]%*%t(a.mat_last) + 4*delta.mat_last%*%t(exp.ic[[it]])%*%t(a.mat_last) + 4*a.mat_last%*%exp.ic[[it]]%*%t(delta.mat_last) +
                              delta.mat_last%*%t(exp.w[[it]]) + exp.w[[it]]%*%t(delta.mat_last) + a.mat_last%*%t(exp.v[[it]]) + exp.v[[it]]%*%t(a.mat_last) + exp.VF[[it]] + covE.t0
            cat("last-gen VY","\n")
            print(exp.VY[[it+1]])
        }

}
    EXP <- list(
        Omega=exp.Omega[[gens]],
        #theta=exp.thetaNT[[gens]],
        Gamma=exp.Gamma[[gens]],
        gc=exp.gc[[gens]],
        hc=exp.hc[[gens]],
        itlo=exp.itlo[[gens]],
        itol=exp.itol[[gens]],
        ic=exp.ic[[gens]],
        VF=exp.VF[[gens]],
        w=exp.w[[gens]],
        q=exp.v[[gens]],
        VY=exp.VY[[gens]],
        mate.cov=mate.cov[[gens]],
        mu=exp.mu[[gens]],
        VGO=exp.VGO[[gens]],
        VGL=exp.VGL[[gens]],
        COVLO=exp.COVLO[[gens]]
        )

        (cov.fin.gen <- exp.VY[[gens]]%*%exp.mu[[gens]]%*%exp.VY[[gens]])
        cor.fin.gen <- cov.fin.gen/exp.VY[[gens]]
        cor.fin.gen[1,2] <- cov.fin.gen[1,2]/(sqrt(exp.VY[[gens]][1,1])*sqrt(exp.VY[[gens]][2,2]))
        cor.fin.gen[2,1] <- cov.fin.gen[2,1]/(sqrt(exp.VY[[gens]][1,1])*sqrt(exp.VY[[gens]][2,2]))
        cor.fin.gen
        rmate.t0 
}
print("true a:")
print(a.mat)
print("true a last gen:")
print(a.mat_last)
print("true delta:")
print(delta.mat)
print("true delta last gen:")
print(delta.mat_last)
print("r2pgs1:")
print(delta.mat[1,1]^2)
print("r2pgs1 last gen:")
print(delta.mat_last[1,1]^2)
print("r2pgs2:")
print(delta.mat[2,2]^2)
print("r2pgs2 last gen:")
print(delta.mat_last[2,2]^2)
}


```

```{r runIterativeMath, eval=FALSE}
iterativeMath(1)
```

```{r runIterativeMath2, eval=FALSE}
iterativeMath(2)
```

```{r runIterativeMath3, eval=FALSE}
iterativeMath(3)
```
```{r runIterativeMath4, eval=FALSE}
iterativeMath(4)
```


```{r runIterativeMath5}
iterativeMath(5)
```